ci: add "Install Composer" step

diff --git a/.github/workflows/php.yaml b/.github/workflows/php.yaml
--- a/.github/workflows/php.yaml
+++ b/.github/workflows/php.yaml
@@ -73,6 +73,23 @@ jobs:
       # Temporary until this repository becomes a mono-repository.
       REMOTE_REPOSITORY: ${{ inputs.project == 'api' && 'dvsa/olcs-backend' || format('dvsa/olcs-{0}', inputs.project) }}
     steps:
+      - name: Install Composer
+        run: |
+          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
+          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+          ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
+          then
+              >&2 echo 'ERROR: Invalid installer checksum'
+              rm composer-setup.php
+              exit 1
+          fi
+
+          php composer-setup.php --quiet
+          RESULT=$?
+          rm composer-setup.php
+          exit $RESULT
       - uses: actions/checkout@v4
         with:
           repository: ${{ env.REMOTE_REPOSITORY }}
